# Generated by Django 3.2.5 on 2021-07-06 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_create', 'Create Permission'), ('can_update', 'Update Permission')]},
        ),
    ]
